package com.carebridge.backend.file.enums;

public enum FilePurpose {
    EXPERT_IDENTITY_SELFIE,
    EXPERT_IDENTITY_CCCD_FRONT,
    EXPERT_IDENTITY_CCCD_BACK,
    EXPERT_CREDENTIAL,
    COMMUNITY_ANSWER_IMAGE,
    MEDICAL_CONTRIBUTION_IMAGE,
    MEDICAL_CONTRIBUTION_DOCUMENT,
    PUBLIC_CONTENT_IMAGE
}