package com.carebridge.backend.audit.entity;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    OTP_SENT,
    OTP_VERIFIED,
    CONSENT_GRANTED,
    CONSENT_REVOKED,
    CREATE_HEALTH_RECORD,
    VIEW_HEALTH_RECORD,
    EXPERT_VERIFICATION,
    MODERATION_ACTION,
    AI_TRIAGE,
    PAYMENT,
    SECURITY_EVENT,
    VIEW_AUDIT_LOG,
    // Expert domain actions
    EXPERT_PROFILE_CREATED,
    EXPERT_PROFILE_UPDATED,
    EXPERT_CREDENTIAL_UPLOADED,
    AVAILABILITY_SLOT_CREATED,
    AVAILABILITY_SLOT_UPDATED,
    AVAILABILITY_SLOT_DELETED,
    CONSULTATION_BOOKED,
    CONSULTATION_CANCELLED,
    CONSULTATION_CONFIRMED,
    REVIEW_SUBMITTED,
    COMMISSION_CALCULATED
}
