package com.carebridge.backend.triage.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.UUID;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.SQLRestriction;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * CB-TRIAGE-CONSENT-IMP-001 (ADR-TDC-001) — AI-triage disclaimer acknowledgement evidence.
 *
 * <p>Maps the canonical consent table {@code data_permissions}, kind-fenced to
 * {@code permission_kind = 'AI_TRIAGE_DISCLAIMER'} so its row set is fully disjoint from the
 * existing {@link com.carebridge.backend.consent.entity.ConsentGrant} rows
 * ({@code permission_kind = 'CONSENT_GRANT'}). Zero schema change: every mapped column exists
 * in baseline {@code B20260724111500__canonical_70_table_baseline.sql}. The identity column
 * {@code legacy_consent_id} is intentionally unmapped ({@code GENERATED BY DEFAULT AS IDENTITY}
 * — the database fills it).
 *
 * <p>Append-style lifecycle (BR-TDC-005): rows are never physically deleted; state changes only
 * via {@code status} / {@code revoked_at} / supersession columns.
 */
@Entity
@Table(name = "data_permissions")
@SQLRestriction("permission_kind = 'AI_TRIAGE_DISCLAIMER'")
@Getter
@Setter
@NoArgsConstructor
public class TriageDisclaimerConsent {

    /** Table PK {@code data_permissions_pkey} (ADR-TDC-001). Assigned by the service. */
    @Id
    @Column(name = "permission_id", nullable = false, updatable = false)
    private UUID permissionId;

    @Column(name = "owner_user_id")
    private UUID ownerUserId;

    @Column(name = "permission_kind", nullable = false, updatable = false, length = 30)
    private String permissionKind = "AI_TRIAGE_DISCLAIMER";

    @Column(name = "scope_type", length = 50)
    private String scopeType;

    @Column(name = "scope_text", columnDefinition = "TEXT")
    private String scopeText;

    @Column(name = "purpose", length = 255)
    private String purpose;

    @Column(name = "policy_version", length = 80)
    private String policyVersion;

    @Column(name = "status", nullable = false, length = 20)
    private String status = "ACTIVE";

    @Column(name = "granted_at")
    private Instant grantedAt;

    /** Always {@code NULL} for disclaimer consent — validity is version match + non-revoked (L5). */
    @Column(name = "expires_at")
    private Instant expiresAt;

    @Column(name = "revoked_at")
    private Instant revokedAt;

    @Column(name = "revoked_by")
    private UUID revokedBy;

    /** Stable id of the user's re-consent chain (seeded with the first row's permission id). */
    @Column(name = "permission_series_id")
    private UUID permissionSeriesId;

    @Column(name = "version_number")
    private Integer versionNumber;

    @Column(name = "supersedes_permission_id")
    private UUID supersedesPermissionId;

    /** SHA-256 hex of the exact disclaimer text that was accepted (ADR-TDC-003). */
    @Column(name = "consent_evidence_key", length = 255)
    private String consentEvidenceKey;

    @Column(name = "locale", length = 20)
    private String locale;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private Instant updatedAt;

    @PrePersist
    void prepareCanonicalPermission() {
        if (permissionId == null) {
            permissionId = UUID.randomUUID();
        }
        permissionKind = "AI_TRIAGE_DISCLAIMER";
        if (status == null || status.isBlank()) {
            status = "ACTIVE";
        }
    }
}
