import { useState } from 'react';
import { PortalShell, Notice } from '../components/PortalShell';
import { updatePartnerProfile } from '../services/partnerApi';
import type { OrganizationType } from '../models/partner';

const initial = { name: '', type: 'CLINIC' as OrganizationType, address: '', city: '', phone: '', email: '', website: '', description: '', logoUrl: '' };
// TODO: load the current profile when a GET /api/v1/partner/profile endpoint is available.
export default function PartnerProfilePage() {
  const [form, setForm] = useState(initial); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const set = (key: keyof typeof initial, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function save() { setSaving(true); setError(null); try { await updatePartnerProfile(form); setMessage('Đã lưu thay đổi hồ sơ đối tác.'); } catch { setError('Không thể lưu hồ sơ. Vui lòng kiểm tra thông tin và thử lại.'); } finally { setSaving(false); } }
  const input = 'mt-2 w-full rounded-2xl border border-outline-variant bg-surface px-4 py-3 text-sm outline-none focus:border-primary';
  return <PortalShell title="Hồ sơ Đối tác"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-3xl font-bold">Thông tin tổ chức</h2><p className="mt-2 text-on-surface-variant">Quản lý và cập nhật hồ sơ hiển thị công khai.</p></div><div className="flex gap-3"><button className="rounded-full border border-primary px-6 py-3 font-semibold text-primary">Hủy</button><button onClick={save} disabled={saving} className="rounded-full bg-primary px-6 py-3 font-semibold text-on-primary disabled:opacity-50">{saving ? 'Đang lưu...' : 'Lưu thay đổi'}</button></div></div>{message && <Notice>{message}</Notice>}{error && <Notice error>{error}</Notice>}
    <div className="mt-7 grid gap-6 lg:grid-cols-3"><section className="rounded-3xl bg-surface p-6 shadow-sm lg:col-span-2"><div className="flex items-center justify-between"><h3 className="text-xl font-bold"><span className="material-symbols-outlined mr-2 text-primary">badge</span>Nhận diện công khai</h3><span className="rounded-full bg-secondary-container px-3 py-1 text-sm text-primary">Đã duyệt</span></div><div className="mt-6 grid gap-4 md:grid-cols-2"><label>Tên tổ chức<input value={form.name} onChange={(e) => set('name', e.target.value)} className={input} /></label><label>Loại hình<select value={form.type} onChange={(e) => set('type', e.target.value)} className={input}><option value="CLINIC">Phòng khám</option><option value="HOSPITAL">Bệnh viện</option><option value="NGO">Tổ chức phi lợi nhuận</option><option value="COMPANY">Công ty</option></select></label><label>Địa chỉ<input value={form.address} onChange={(e) => set('address', e.target.value)} className={input} /></label><label>Thành phố<input value={form.city} onChange={(e) => set('city', e.target.value)} className={input} /></label></div><label className="mt-6 block">Mô tả hiển thị<textarea rows={5} value={form.description} onChange={(e) => set('description', e.target.value)} className={input} /></label></section><section className="rounded-3xl bg-surface p-6 shadow-sm"><h3 className="text-xl font-bold"><span className="material-symbols-outlined mr-2 text-primary">contact_phone</span>Liên hệ chính</h3><label className="mt-5 block">Email hỗ trợ<input type="email" value={form.email} onChange={(e) => set('email', e.target.value)} className={input} /></label><label className="mt-4 block">Hotline<input value={form.phone} onChange={(e) => set('phone', e.target.value)} className={input} /></label><label className="mt-4 block">Website<input value={form.website} onChange={(e) => set('website', e.target.value)} className={input} /></label><div className="mt-7 rounded-2xl bg-surface-container-low p-4 text-sm text-on-surface-variant">Cơ sở được duyệt sẽ hiển thị khi API quản lý cơ sở được cung cấp.</div></section></div></PortalShell>;
}
