import { useEffect, useState } from 'react';
import { PortalShell, Notice } from '../components/PortalShell';
import { fetchPartnerServices, submitServiceListing } from '../services/partnerApi';
import type { PartnerServiceListItem } from '../models/partner';

export default function ServiceListingsPage() {
  const [items, setItems] = useState<PartnerServiceListItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: '', category: 'Sức khỏe', location: 'Trực tuyến', description: '', eligibility: '', routing: 'CUSTOMER_SELECTS' as 'CUSTOMER_SELECTS' | 'AUTO_ASSIGN' });
  const load = () => { setLoading(true); fetchPartnerServices().then((page) => setItems(page.content)).catch(() => setError('Không thể tải danh sách dịch vụ.')).finally(() => setLoading(false)); };
  useEffect(load, []);
  async function submit() { try { await submitServiceListing(form); setOpen(false); load(); } catch { setError('Không thể gửi dịch vụ.'); } }
  return <PortalShell title="Danh mục Dịch vụ"><div className="flex justify-between"><h2 className="text-2xl font-bold">Danh mục Dịch vụ</h2><button onClick={() => setOpen(true)} className="rounded-full bg-primary px-6 py-3 text-on-primary">+ Thêm dịch vụ</button></div>{error && <div className="mt-4"><Notice error>{error}</Notice></div>}{loading ? <p className="mt-8">Đang tải dịch vụ...</p> : items.length === 0 ? <p className="mt-8 rounded-3xl bg-surface p-8 text-on-surface-variant">Chưa có dịch vụ nào.</p> : <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item.id} className="rounded-2xl bg-surface p-6"><h3 className="text-lg font-bold">{item.serviceName}</h3><p className="mt-3 text-sm text-on-surface-variant">{item.description}</p><div className="mt-5 flex justify-between border-t border-outline-variant pt-4"><span>{item.priceFrom ? `${item.priceFrom.toLocaleString()} ${item.currency}` : 'Liên hệ'}</span><span className="rounded-full bg-secondary-container px-3 py-1 text-sm text-primary">{item.approvalStatus}</span></div></article>)}</div>}{open && <div className="fixed inset-0 z-10 flex justify-end bg-scrim/30"><form onSubmit={(e) => { e.preventDefault(); submit(); }} className="h-full w-full max-w-md bg-surface p-7"><h2 className="text-xl font-bold">Thêm dịch vụ mới</h2><input required placeholder="Tên dịch vụ" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-5 w-full rounded-xl border p-3" /><textarea required placeholder="Mô tả" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="mt-4 w-full rounded-xl border p-3" /><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)}>Hủy</button><button className="rounded-full bg-primary px-5 py-3 text-on-primary">Gửi duyệt</button></div></form></div>}</PortalShell>;
}
