-- Phase 2 wave 9 cutover: audit, consent, expenses, and approved domain archives.

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '5min';

ALTER TABLE public.audit_events
  ADD COLUMN IF NOT EXISTS event_origin varchar(40) NOT NULL DEFAULT 'AUDIT_LOG',
  ADD COLUMN IF NOT EXISTS ip_address varchar(80);

-- The immutable trigger remains the final-state policy. It is disabled only while
-- restoring source columns into rows copied by the earlier additive migration.
ALTER TABLE public.audit_events DISABLE TRIGGER audit_events_immutable_trg;
UPDATE public.audit_events
   SET event_origin='SECURITY_INVESTIGATION_NOTE'
 WHERE event_category='SECURITY_INVESTIGATION_NOTE';
INSERT INTO public.audit_events (
    audit_event_id,actor_user_id,event_category,resource_type,resource_id,
    before_payload_jsonb,after_payload_jsonb,occurred_at,created_at,event_origin,ip_address)
SELECT audit_log_id,actor_user_id,action,entity_type,entity_id,old_value_json,
       new_value_json,created_at,created_at,'AUDIT_LOG',ip_address
  FROM public.audit_logs
ON CONFLICT (audit_event_id) DO NOTHING;
UPDATE public.audit_events a
   SET event_origin='AUDIT_LOG',ip_address=l.ip_address,
       actor_user_id=l.actor_user_id,event_category=l.action,
       resource_type=l.entity_type,resource_id=l.entity_id,
       before_payload_jsonb=l.old_value_json,after_payload_jsonb=l.new_value_json,
       occurred_at=l.created_at,created_at=l.created_at
  FROM public.audit_logs l
 WHERE a.audit_event_id=l.audit_log_id;
ALTER TABLE public.audit_events ENABLE TRIGGER audit_events_immutable_trg;

ALTER TABLE public.data_permissions
  ALTER COLUMN permission_id SET DEFAULT gen_random_uuid(),
  ALTER COLUMN status SET DEFAULT 'ACTIVE',
  ADD COLUMN IF NOT EXISTS legacy_consent_id bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS permission_kind varchar(30) NOT NULL DEFAULT 'DATA_PERMISSION',
  ADD COLUMN IF NOT EXISTS recipient varchar(120),
  ADD COLUMN IF NOT EXISTS scope_text text,
  ADD COLUMN IF NOT EXISTS evidence_key uuid,
  ADD COLUMN IF NOT EXISTS locale varchar(20);

CREATE UNIQUE INDEX IF NOT EXISTS data_permissions_legacy_consent_id_uk
  ON public.data_permissions(legacy_consent_id) WHERE legacy_consent_id IS NOT NULL;

INSERT INTO public.data_permissions (
    permission_id,legacy_consent_id,permission_kind,owner_user_id,scope_type,purpose,
    recipient,scope_text,policy_version,evidence_key,consent_evidence_key,locale,
    granted_at,expires_at,revoked_at,revoked_by,status,version_number,
    permission_series_id,supersedes_permission_id,created_at,updated_at)
SELECT (md5('consent-grant:'||c.id::text))::uuid,c.id,'CONSENT_GRANT',c.user_id,
       c.data_type,c.purpose,c.recipient,c.scope_text,c.policy_version,c.evidence_key,
       c.evidence_key::text,c.locale,c.consent_given_at,c.expiry_at,c.revoked_at,
       c.revoked_by,CASE WHEN c.revoked_at IS NOT NULL THEN 'REVOKED'
                         WHEN c.expiry_at <= now() THEN 'EXPIRED' ELSE 'ACTIVE' END,
       c.version,(md5('consent-series:'||c.user_id::text||':'||c.data_type||':'||
         c.purpose||':'||coalesce(c.recipient,'')))::uuid,
       lag((md5('consent-grant:'||c.id::text))::uuid) OVER (
         PARTITION BY c.user_id,c.data_type,c.purpose,coalesce(c.recipient,'')
         ORDER BY c.version,c.consent_given_at,c.id),
       c.created_at,c.updated_at
  FROM public.consent_grants c
ON CONFLICT (permission_id) DO UPDATE SET
  legacy_consent_id=excluded.legacy_consent_id,permission_kind='CONSENT_GRANT',
  owner_user_id=excluded.owner_user_id,scope_type=excluded.scope_type,
  purpose=excluded.purpose,recipient=excluded.recipient,scope_text=excluded.scope_text,
  policy_version=excluded.policy_version,evidence_key=excluded.evidence_key,
  consent_evidence_key=excluded.consent_evidence_key,locale=excluded.locale,
  granted_at=excluded.granted_at,expires_at=excluded.expires_at,
  revoked_at=excluded.revoked_at,revoked_by=excluded.revoked_by,status=excluded.status,
  version_number=excluded.version_number,permission_series_id=excluded.permission_series_id,
  supersedes_permission_id=excluded.supersedes_permission_id,updated_at=excluded.updated_at;

INSERT INTO public.expense_entries (
    expense_entry_id,owner_user_id,care_subject_id,mother_journey_id,category,
    amount,currency,expense_date,note,created_at,updated_at)
SELECT expense_id,owner_user_id,baby_id,journey_id,category,amount,currency,
       expense_date,note,created_at,updated_at
  FROM public.expenses
ON CONFLICT (expense_entry_id) DO UPDATE SET
  owner_user_id=excluded.owner_user_id,care_subject_id=excluded.care_subject_id,
  mother_journey_id=excluded.mother_journey_id,category=excluded.category,
  amount=excluded.amount,currency=excluded.currency,expense_date=excluded.expense_date,
  note=excluded.note,updated_at=excluded.updated_at;

ALTER TABLE public.archived_records
  ALTER COLUMN payload_jsonb SET DEFAULT '{}'::jsonb,
  ALTER COLUMN archive_reason SET DEFAULT 'RUNTIME_COMPATIBILITY',
  ALTER COLUMN source_schema_version SET DEFAULT 'PHASE2_WAVE9',
  ALTER COLUMN checksum SET DEFAULT md5(gen_random_uuid()::text),
  ADD COLUMN IF NOT EXISTS configured_by uuid,
  ADD COLUMN IF NOT EXISTS channel_type varchar(30),
  ADD COLUMN IF NOT EXISTS duration_minutes smallint,
  ADD COLUMN IF NOT EXISTS specialty_scope varchar(100),
  ADD COLUMN IF NOT EXISTS minimum_price numeric,
  ADD COLUMN IF NOT EXISTS maximum_price numeric,
  ADD COLUMN IF NOT EXISTS commission_rate numeric,
  ADD COLUMN IF NOT EXISTS currency varchar(10),
  ADD COLUMN IF NOT EXISTS effective_from timestamptz,
  ADD COLUMN IF NOT EXISTS effective_to timestamptz,
  ADD COLUMN IF NOT EXISTS status varchar(30),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz,
  ADD COLUMN IF NOT EXISTS expert_profile_id uuid,
  ADD COLUMN IF NOT EXISTS price_band_id uuid,
  ADD COLUMN IF NOT EXISTS price_amount numeric,
  ADD COLUMN IF NOT EXISTS cancellation_policy text,
  ADD COLUMN IF NOT EXISTS version_no integer,
  ADD COLUMN IF NOT EXISTS requester_user_id uuid,
  ADD COLUMN IF NOT EXISTS availability_id uuid,
  ADD COLUMN IF NOT EXISTS expert_price_id uuid,
  ADD COLUMN IF NOT EXISTS shared_summary_id uuid,
  ADD COLUMN IF NOT EXISTS topic varchar(500),
  ADD COLUMN IF NOT EXISTS scheduled_start timestamptz,
  ADD COLUMN IF NOT EXISTS scheduled_end timestamptz,
  ADD COLUMN IF NOT EXISTS price_snapshot_amount numeric,
  ADD COLUMN IF NOT EXISTS commission_rate_snapshot numeric,
  ADD COLUMN IF NOT EXISTS cancellation_policy_snapshot text,
  ADD COLUMN IF NOT EXISTS price_locked_at timestamptz,
  ADD COLUMN IF NOT EXISTS booking_id uuid,
  ADD COLUMN IF NOT EXISTS communication_room_id varchar(255),
  ADD COLUMN IF NOT EXISTS started_at timestamptz,
  ADD COLUMN IF NOT EXISTS ended_at timestamptz,
  ADD COLUMN IF NOT EXISTS session_status varchar(30),
  ADD COLUMN IF NOT EXISTS expert_summary text,
  ADD COLUMN IF NOT EXISTS technical_log_json jsonb,
  ADD COLUMN IF NOT EXISTS conversation_id uuid,
  ADD COLUMN IF NOT EXISTS mother_user_id uuid,
  ADD COLUMN IF NOT EXISTS expert_user_id uuid,
  ADD COLUMN IF NOT EXISTS last_activity_at timestamptz,
  ADD COLUMN IF NOT EXISTS mother_last_read_at timestamptz,
  ADD COLUMN IF NOT EXISTS mother_last_read_message_id uuid,
  ADD COLUMN IF NOT EXISTS expert_last_read_at timestamptz,
  ADD COLUMN IF NOT EXISTS expert_last_read_message_id uuid,
  ADD COLUMN IF NOT EXISTS sender_user_id uuid,
  ADD COLUMN IF NOT EXISTS client_message_id uuid,
  ADD COLUMN IF NOT EXISTS message_type varchar(30),
  ADD COLUMN IF NOT EXISTS message_body text,
  ADD COLUMN IF NOT EXISTS initiated_by_user_id uuid,
  ADD COLUMN IF NOT EXISTS call_type varchar(10),
  ADD COLUMN IF NOT EXISTS call_status varchar(20),
  ADD COLUMN IF NOT EXISTS zego_room_id varchar(255),
  ADD COLUMN IF NOT EXISTS initiated_at timestamptz,
  ADD COLUMN IF NOT EXISTS answered_at timestamptz,
  ADD COLUMN IF NOT EXISTS duration_seconds integer,
  ADD COLUMN IF NOT EXISTS name varchar(200),
  ADD COLUMN IF NOT EXISTS organization_type varchar(20),
  ADD COLUMN IF NOT EXISTS address varchar(500),
  ADD COLUMN IF NOT EXISTS city varchar(100),
  ADD COLUMN IF NOT EXISTS phone varchar(20),
  ADD COLUMN IF NOT EXISTS email varchar(255),
  ADD COLUMN IF NOT EXISTS website varchar(500),
  ADD COLUMN IF NOT EXISTS logo_url varchar(1000),
  ADD COLUMN IF NOT EXISTS description varchar(2000),
  ADD COLUMN IF NOT EXISTS organization_status varchar(30),
  ADD COLUMN IF NOT EXISTS representative_user_id uuid;

DO $wave9_collision_gate$
BEGIN
  IF EXISTS (
    SELECT source_id FROM (
      SELECT price_band_id source_id FROM public.consultation_price_bands
      UNION ALL SELECT expert_price_id FROM public.expert_consultation_prices
      UNION ALL SELECT booking_id FROM public.consultation_bookings
      UNION ALL SELECT session_id FROM public.consultation_sessions
      UNION ALL SELECT conversation_id FROM public.direct_conversations
      UNION ALL SELECT message_id FROM public.direct_messages
      UNION ALL SELECT call_id FROM public.conversation_calls
    ) x GROUP BY source_id HAVING count(*) > 1
  ) THEN RAISE EXCEPTION 'WAVE9_ID_COLLISION: archived records'; END IF;
END $wave9_collision_gate$;

DELETE FROM public.archived_records WHERE legacy_table IN (
  'consultation_price_bands','expert_consultation_prices','consultation_bookings','consultation_sessions',
  'direct_conversations','direct_messages','conversation_calls','partner_organizations');

INSERT INTO public.archived_records (
    archive_id,legacy_table,legacy_id,owner_user_id,payload_jsonb,original_created_at,
    archive_reason,source_schema_version,checksum,configured_by,channel_type,
    duration_minutes,specialty_scope,minimum_price,maximum_price,commission_rate,
    currency,effective_from,effective_to,status,updated_at)
SELECT price_band_id,'consultation_price_bands',price_band_id::text,configured_by,
       to_jsonb(b),created_at,'PHASE2_DOMAIN_ARCHIVE','PHASE2_WAVE9',md5(to_jsonb(b)::text),
       configured_by,channel_type,duration_minutes,specialty_scope,minimum_price,
       maximum_price,commission_rate,currency,effective_from,effective_to,status,updated_at
  FROM public.consultation_price_bands b;

INSERT INTO public.archived_records (
    archive_id,legacy_table,legacy_id,payload_jsonb,original_created_at,archive_reason,
    source_schema_version,checksum,expert_profile_id,price_band_id,channel_type,
    duration_minutes,price_amount,currency,cancellation_policy,effective_from,effective_to,
    status,version_no,updated_at)
SELECT expert_price_id,'expert_consultation_prices',expert_price_id::text,to_jsonb(p),created_at,
       'PHASE2_DOMAIN_ARCHIVE','PHASE2_WAVE9',md5(to_jsonb(p)::text),expert_profile_id,
       price_band_id,channel_type,duration_minutes,price_amount,currency,cancellation_policy,
       effective_from,effective_to,status,version_no,updated_at
  FROM public.expert_consultation_prices p;

INSERT INTO public.archived_records (
    archive_id,legacy_table,legacy_id,owner_user_id,payload_jsonb,original_created_at,
    archive_reason,source_schema_version,checksum,requester_user_id,expert_profile_id,
    availability_id,expert_price_id,shared_summary_id,topic,channel_type,duration_minutes,
    scheduled_start,scheduled_end,price_snapshot_amount,commission_rate_snapshot,currency,
    cancellation_policy_snapshot,price_locked_at,status,updated_at)
SELECT booking_id,'consultation_bookings',booking_id::text,requester_user_id,to_jsonb(b),created_at,
       'PHASE2_DOMAIN_ARCHIVE','PHASE2_WAVE9',md5(to_jsonb(b)::text),requester_user_id,
       expert_profile_id,availability_id,expert_price_id,shared_summary_id,topic,channel_type,
       duration_minutes,scheduled_start,scheduled_end,price_snapshot_amount,
       commission_rate_snapshot,currency,cancellation_policy_snapshot,price_locked_at,status,updated_at
  FROM public.consultation_bookings b;

INSERT INTO public.archived_records (
    archive_id,legacy_table,legacy_id,payload_jsonb,original_created_at,archive_reason,
    source_schema_version,checksum,booking_id,communication_room_id,started_at,ended_at,
    session_status,expert_summary,technical_log_json,updated_at)
SELECT session_id,'consultation_sessions',session_id::text,to_jsonb(s),created_at,
       'PHASE2_DOMAIN_ARCHIVE','PHASE2_WAVE9',md5(to_jsonb(s)::text),booking_id,
       communication_room_id,started_at,ended_at,session_status,expert_summary,
       technical_log_json,updated_at
  FROM public.consultation_sessions s;

INSERT INTO public.archived_records (
    archive_id,legacy_table,legacy_id,owner_user_id,payload_jsonb,original_created_at,
    archive_reason,source_schema_version,checksum,conversation_id,mother_user_id,
    expert_user_id,status,last_activity_at,mother_last_read_at,mother_last_read_message_id,
    expert_last_read_at,expert_last_read_message_id)
SELECT conversation_id,'direct_conversations',conversation_id::text,mother_user_id,to_jsonb(c),
       created_at,'PHASE2_DOMAIN_ARCHIVE','PHASE2_WAVE9',md5(to_jsonb(c)::text),conversation_id,
       mother_user_id,expert_user_id,status,last_activity_at,mother_last_read_at,
       mother_last_read_message_id,expert_last_read_at,expert_last_read_message_id
  FROM public.direct_conversations c;

INSERT INTO public.archived_records (
    archive_id,legacy_table,legacy_id,owner_user_id,payload_jsonb,original_created_at,
    archive_reason,source_schema_version,checksum,conversation_id,sender_user_id,
    client_message_id,message_type,message_body)
SELECT message_id,'direct_messages',message_id::text,sender_user_id,to_jsonb(m),created_at,
       'PHASE2_DOMAIN_ARCHIVE','PHASE2_WAVE9',md5(to_jsonb(m)::text),conversation_id,
       sender_user_id,client_message_id,message_type,message_body
  FROM public.direct_messages m;

INSERT INTO public.archived_records (
    archive_id,legacy_table,legacy_id,owner_user_id,payload_jsonb,original_created_at,
    archive_reason,source_schema_version,checksum,conversation_id,initiated_by_user_id,
    call_type,call_status,zego_room_id,initiated_at,answered_at,ended_at,duration_seconds)
SELECT call_id,'conversation_calls',call_id::text,initiated_by_user_id,to_jsonb(c),created_at,
       'PHASE2_DOMAIN_ARCHIVE','PHASE2_WAVE9',md5(to_jsonb(c)::text),conversation_id,
       initiated_by_user_id,call_type,call_status,zego_room_id,initiated_at,answered_at,
       ended_at,duration_seconds
  FROM public.conversation_calls c;

INSERT INTO public.archived_records (
    archive_id,legacy_table,legacy_id,owner_user_id,payload_jsonb,original_created_at,
    archive_reason,source_schema_version,checksum,name,organization_type,address,city,
    phone,email,website,logo_url,description,organization_status,representative_user_id,updated_at)
SELECT partner_id,'partner_organizations',partner_id::text,representative_user_id,to_jsonb(p),
       created_at,'PHASE2_DOMAIN_ARCHIVE','PHASE2_WAVE9',md5(to_jsonb(p)::text),name,type,
       address,city,phone,email,website,logo_url,description,status,representative_user_id,updated_at
  FROM public.partner_organizations p;

DO $wave9_reconcile$
BEGIN
  IF (SELECT count(*) FROM public.audit_logs) <>
     (SELECT count(*) FROM public.audit_events WHERE event_origin='AUDIT_LOG') THEN
    RAISE EXCEPTION 'WAVE9_RECONCILIATION: audit logs';
  END IF;
  IF (SELECT count(*) FROM public.security_events) <>
     (SELECT count(*) FROM public.audit_events WHERE event_category IN ('LOGIN_FAILED', 'PERMISSION_DENIED', 'SUSPICIOUS_ACTIVITY', 'TOKEN_REVOKED', 'OTP_ATTEMPT_LIMIT_EXCEEDED')) THEN
    RAISE EXCEPTION 'WAVE9_RECONCILIATION: security events';
  END IF;
  IF (SELECT count(*) FROM public.consent_grants) <>
     (SELECT count(*) FROM public.data_permissions WHERE permission_kind='CONSENT_GRANT') THEN
    RAISE EXCEPTION 'WAVE9_RECONCILIATION: consent grants';
  END IF;
  IF (SELECT count(*) FROM public.expenses) <> (SELECT count(*) FROM public.expense_entries) THEN
    RAISE EXCEPTION 'WAVE9_RECONCILIATION: expenses';
  END IF;
  IF (SELECT count(*) FROM public.consultation_price_bands) <>
     (SELECT count(*) FROM public.archived_records WHERE legacy_table='consultation_price_bands') OR
     (SELECT count(*) FROM public.expert_consultation_prices) <>
     (SELECT count(*) FROM public.archived_records WHERE legacy_table='expert_consultation_prices') OR
     (SELECT count(*) FROM public.consultation_bookings) <>
     (SELECT count(*) FROM public.archived_records WHERE legacy_table='consultation_bookings') OR
     (SELECT count(*) FROM public.consultation_sessions) <>
     (SELECT count(*) FROM public.archived_records WHERE legacy_table='consultation_sessions') THEN
    RAISE EXCEPTION 'WAVE9_RECONCILIATION: consultation archive';
  END IF;
  IF (SELECT count(*) FROM public.direct_conversations) <>
     (SELECT count(*) FROM public.archived_records WHERE legacy_table='direct_conversations') OR
     (SELECT count(*) FROM public.direct_messages) <>
     (SELECT count(*) FROM public.archived_records WHERE legacy_table='direct_messages') OR
     (SELECT count(*) FROM public.conversation_calls) <>
     (SELECT count(*) FROM public.archived_records WHERE legacy_table='conversation_calls') THEN
    RAISE EXCEPTION 'WAVE9_RECONCILIATION: realtime archive';
  END IF;
  IF (SELECT count(*) FROM public.partner_organizations) <>
     (SELECT count(*) FROM public.archived_records WHERE legacy_table='partner_organizations') THEN
    RAISE EXCEPTION 'WAVE9_RECONCILIATION: partner archive';
  END IF;
  IF EXISTS (SELECT 1 FROM public.archived_records r
              LEFT JOIN public.archived_records c ON c.archive_id=r.conversation_id
                AND c.legacy_table='direct_conversations'
              WHERE r.legacy_table IN ('direct_messages','conversation_calls') AND c.archive_id IS NULL) OR
     EXISTS (SELECT 1 FROM public.data_permissions p LEFT JOIN public.users u
                ON u.user_id=p.owner_user_id
              WHERE p.permission_kind='CONSENT_GRANT' AND u.user_id IS NULL) THEN
    RAISE EXCEPTION 'WAVE9_ORPHAN_TARGET';
  END IF;
END $wave9_reconcile$;

ALTER TABLE public.care_facilities DROP CONSTRAINT IF EXISTS care_facilities_partner_id_fkey;
ALTER TABLE public.care_facilities ADD CONSTRAINT care_facilities_partner_archive_fk
  FOREIGN KEY (partner_id) REFERENCES public.archived_records(archive_id);

CREATE INDEX IF NOT EXISTS audit_events_origin_time_ix
  ON public.audit_events(event_origin,occurred_at DESC);
CREATE INDEX IF NOT EXISTS data_permissions_consent_owner_ix
  ON public.data_permissions(owner_user_id,granted_at DESC)
  WHERE permission_kind='CONSENT_GRANT';
CREATE INDEX IF NOT EXISTS archived_consultation_booking_requester_ix
  ON public.archived_records(requester_user_id,status,original_created_at DESC)
  WHERE legacy_table='consultation_bookings';
CREATE UNIQUE INDEX IF NOT EXISTS archived_realtime_conversation_pair_uk
  ON public.archived_records(mother_user_id,expert_user_id)
  WHERE legacy_table='direct_conversations';
CREATE UNIQUE INDEX IF NOT EXISTS archived_realtime_message_client_uk
  ON public.archived_records(conversation_id,sender_user_id,client_message_id)
  WHERE legacy_table='direct_messages';
CREATE INDEX IF NOT EXISTS archived_realtime_message_timeline_ix
  ON public.archived_records(conversation_id,original_created_at DESC)
  WHERE legacy_table='direct_messages';
CREATE INDEX IF NOT EXISTS archived_realtime_call_timeline_ix
  ON public.archived_records(conversation_id,initiated_at DESC)
  WHERE legacy_table='conversation_calls';
CREATE UNIQUE INDEX IF NOT EXISTS archived_partner_email_uk
  ON public.archived_records(email) WHERE legacy_table='partner_organizations';
CREATE UNIQUE INDEX IF NOT EXISTS archived_partner_representative_uk
  ON public.archived_records(representative_user_id)
  WHERE legacy_table='partner_organizations';

ALTER TABLE public.archived_records
  ADD CONSTRAINT archived_realtime_conversation_fk
  FOREIGN KEY (conversation_id) REFERENCES public.archived_records(archive_id),
  ADD CONSTRAINT archived_realtime_mother_fk FOREIGN KEY (mother_user_id) REFERENCES public.users(user_id),
  ADD CONSTRAINT archived_realtime_expert_fk FOREIGN KEY (expert_user_id) REFERENCES public.users(user_id),
  ADD CONSTRAINT archived_realtime_sender_fk FOREIGN KEY (sender_user_id) REFERENCES public.users(user_id),
  ADD CONSTRAINT archived_realtime_initiator_fk FOREIGN KEY (initiated_by_user_id) REFERENCES public.users(user_id);
ALTER TABLE public.archived_records
  ADD CONSTRAINT archived_realtime_conversation_shape_ck CHECK (
    legacy_table <> 'direct_conversations' OR
    (mother_user_id IS NOT NULL AND expert_user_id IS NOT NULL AND status='ACTIVE'
     AND original_created_at IS NOT NULL
     AND (last_activity_at IS NULL OR last_activity_at >= original_created_at))),
  ADD CONSTRAINT archived_realtime_message_shape_ck CHECK (
    legacy_table <> 'direct_messages' OR
    (conversation_id IS NOT NULL AND sender_user_id IS NOT NULL AND client_message_id IS NOT NULL
     AND message_type='TEXT' AND length(btrim(message_body)) BETWEEN 1 AND 2000
     AND original_created_at IS NOT NULL)),
  ADD CONSTRAINT archived_realtime_call_shape_ck CHECK (
    legacy_table <> 'conversation_calls' OR
    (conversation_id IS NOT NULL AND initiated_by_user_id IS NOT NULL
     AND call_type IN ('VOICE','VIDEO')
     AND call_status IN ('INITIATED','RINGING','ANSWERED','DECLINED','MISSED','CANCELLED','ENDED','FAILED')
     AND zego_room_id IS NOT NULL AND initiated_at IS NOT NULL AND original_created_at IS NOT NULL
     AND (duration_seconds IS NULL OR duration_seconds >= 0)
     AND (answered_at IS NULL OR answered_at >= initiated_at)
     AND (ended_at IS NULL OR ended_at >= initiated_at)
     AND (call_status <> 'ENDED' OR answered_at IS NOT NULL)));
ALTER TABLE public.archived_records
  ADD CONSTRAINT archived_consultation_configured_by_fk
  FOREIGN KEY (configured_by) REFERENCES public.users(user_id),
  ADD CONSTRAINT archived_consultation_requester_fk
  FOREIGN KEY (requester_user_id) REFERENCES public.users(user_id),
  ADD CONSTRAINT archived_consultation_availability_fk
  FOREIGN KEY (availability_id) REFERENCES public.expert_availability(availability_id),
  ADD CONSTRAINT archived_consultation_price_band_fk
  FOREIGN KEY (price_band_id) REFERENCES public.archived_records(archive_id),
  ADD CONSTRAINT archived_consultation_expert_price_fk
  FOREIGN KEY (expert_price_id) REFERENCES public.archived_records(archive_id),
  ADD CONSTRAINT archived_consultation_booking_fk
  FOREIGN KEY (booking_id) REFERENCES public.archived_records(archive_id);
ALTER TABLE public.archived_records
  ADD CONSTRAINT archived_partner_representative_fk
  FOREIGN KEY (representative_user_id) REFERENCES public.users(user_id),
  ADD CONSTRAINT archived_partner_shape_ck CHECK (
    legacy_table <> 'partner_organizations' OR
    (name IS NOT NULL AND organization_type IN ('CLINIC','HOSPITAL','NGO','COMPANY')
     AND address IS NOT NULL AND city IS NOT NULL AND phone IS NOT NULL AND email IS NOT NULL
     AND organization_status IN ('PENDING_APPROVAL','APPROVED','SUSPENDED','REJECTED')
     AND representative_user_id IS NOT NULL AND original_created_at IS NOT NULL));

DO $wave9_dependency_gate$
DECLARE source_oid oid; source_name text; dependency_count bigint;
BEGIN
  FOREACH source_name IN ARRAY ARRAY[
    'audit_logs','consent_grants','consultation_bookings','consultation_price_bands',
    'consultation_sessions','conversation_calls','direct_conversations','direct_messages',
    'expenses','expert_consultation_prices','partner_organizations','security_events','security_event_notes'
  ] LOOP
    source_oid:=to_regclass('public.'||source_name);
    SELECT count(*) INTO dependency_count FROM pg_constraint
     WHERE contype='f' AND confrelid=source_oid
       AND conrelid <> ALL (ARRAY[
         'public.consultation_bookings'::regclass,
         'public.consultation_sessions'::regclass,
         'public.expert_consultation_prices'::regclass,
         'public.conversation_calls'::regclass,
         'public.direct_messages'::regclass
       ]);
    IF dependency_count > 0 THEN
      RAISE EXCEPTION 'WAVE9_RETAINED_INBOUND_FK: % has %',source_name,dependency_count;
    END IF;
    SELECT count(DISTINCT v.oid) INTO dependency_count
      FROM pg_depend d JOIN pg_rewrite r ON r.oid=d.objid JOIN pg_class v ON v.oid=r.ev_class
     WHERE d.refobjid=source_oid AND v.relkind IN ('v','m');
    IF dependency_count > 0 THEN
      RAISE EXCEPTION 'WAVE9_DEPENDENT_VIEW: % has %',source_name,dependency_count;
    END IF;
  END LOOP;
END $wave9_dependency_gate$;

DROP TABLE IF EXISTS public.consultation_sessions;
DROP TABLE IF EXISTS public.consultation_bookings;
DROP TABLE IF EXISTS public.expert_consultation_prices;
DROP TABLE IF EXISTS public.consultation_price_bands;
DROP TABLE IF EXISTS public.conversation_calls;
DROP TABLE IF EXISTS public.direct_messages;
DROP TABLE IF EXISTS public.direct_conversations;
DROP TABLE IF EXISTS public.audit_logs;
DROP TABLE IF EXISTS public.consent_grants;
DROP TABLE IF EXISTS public.expenses;
DROP TABLE IF EXISTS public.partner_organizations;
DROP TABLE IF EXISTS public.security_event_notes;
DROP TABLE IF EXISTS public.security_events;

DO $wave9_absence_gate$
DECLARE name text;
BEGIN
  FOREACH name IN ARRAY ARRAY[
    'audit_logs','consent_grants','consultation_bookings','consultation_price_bands',
    'consultation_sessions','conversation_calls','direct_conversations','direct_messages',
    'expenses','expert_consultation_prices','partner_organizations','security_events','security_event_notes'
  ] LOOP
    IF to_regclass('public.'||name) IS NOT NULL THEN
      RAISE EXCEPTION 'WAVE9_DROP_FAILED: %',name;
    END IF;
  END LOOP;
END $wave9_absence_gate$;
