package com.carebridge.backend.consultation.entity;

import com.carebridge.backend.expert.enums.ConsultationModality;
import com.carebridge.backend.expert.enums.ConsultationStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;

/**
 * Consultation booking entity.
 * Represents a scheduled consultation between a user and an expert.
 *
 * Follows state machine:
 * PENDING_PAYMENT -> CONFIRMED/CANCELLED
 * CONFIRMED -> IN_PROGRESS/CANCELLED/RESCHEDULED
 * IN_PROGRESS -> COMPLETED/NO_SHOW
 *
 * Maps to ERD: consultation_bookings (PK: booking_id)
 */
@Entity
@Table(name = "consultation_bookings")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Consultation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "booking_id")
    private Long bookingId;

    /**
     * Unique booking reference shown to users.
     * Format: BK-YYYYMMDD-XXX
     */
    @Column(name = "booking_ref", nullable = false, unique = true, length = 100)
    private String bookingRef;

    /**
     * Foreign key to experts table (expert_profiles).
     */
    @Column(name = "expert_id", nullable = false)
    private Long expertId;

    /**
     * User who requested/books the consultation.
     */
    @Column(name = "requester_user_id", nullable = false)
    private Long requesterUserId;

    /**
     * Linked availability slot (if booked from available slot).
     * Can be null for direct booking without pre-allocated slot.
     * FK to expert_availability.availability_id
     */
    @Column(name = "availability_id")
    private Long availabilityId;

    /**
     * Foreign key to expert_consultation_prices table.
     * ERD: expert_price_id
     */
    @Column(name = "expert_price_id")
    private Long expertPriceId;

    /**
     * Reference to shared health summary (optional).
     * FK to health_summaries.summary_id
     * ERD: shared_summary_id
     */
    @Column(name = "shared_summary_id")
    private Long sharedSummaryId;

    /**
     * Consultation topic/subject.
     * ERD: topic
     */
    @Column(name = "topic", length = 500)
    private String topic;

    /**
     * Consultation modality/channel.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "channel_type", nullable = false, length = 50)
    private ConsultationModality channelType;

    /**
     * Duration of consultation in minutes.
     */
    @Column(name = "duration_minutes", nullable = false)
    private Integer durationMinutes;

    /**
     * Scheduled start time of the consultation.
     */
    @Column(name = "scheduled_start", nullable = false)
    private Instant scheduledStart;

    /**
     * Scheduled end time of the consultation.
     * Must be scheduled_start + duration_minutes.
     */
    @Column(name = "scheduled_end", nullable = false)
    private Instant scheduledEnd;

    /**
     * Current consultation status.
     * Follows state machine transitions.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 50)
    private ConsultationStatus status;

    /**
     * Price at the time of booking (in smallest currency unit, e.g., VND).
     * Snapshot for historical accuracy - immune to future price changes.
     * ADR-EXP-005: Versioned pricing with snapshot.
     */
    @Column(name = "price_snapshot_amount", nullable = false)
    private Integer priceSnapshotAmount;

    /**
     * Commission rate snapshot (e.g., 0.20 for 20%).
     */
    @Column(name = "commission_rate_snapshot", precision = 5, scale = 4)
    private Double commissionRateSnapshot;

    /**
     * Currency code (VND, USD, etc.).
     */
    @Column(name = "currency", nullable = false, length = 10)
    @Builder.Default
    private String currency = "VND";

    /**
     * Cancellation policy snapshot (JSON or text).
     */
    @Column(name = "cancellation_policy_snapshot", columnDefinition = "TEXT")
    private String cancellationPolicySnapshot;

    /**
     * When the price was locked/snapshot.
     */
    @Column(name = "price_locked_at", nullable = false)
    @Builder.Default
    private Instant priceLockedAt = Instant.now();

    /**
     * Reference to payment transaction.
     * FK to payment_transactions.payment_id
     */
    @Column(name = "payment_transaction_id")
    private Long paymentTransactionId;

    /**
     * Realtime session token for the consultation.
     * Generated by RealtimeService.
     */
    @Column(name = "session_token")
    private String sessionToken;

    /**
     * Expert's summary after the consultation.
     */
    @Column(name = "expert_summary", columnDefinition = "TEXT")
    private String expertSummary;

    /**
     * Technical logs (JSON) for debugging/audit.
     */
    @Column(name = "technical_log_json", columnDefinition = "JSONB")
    private String technicalLogJson;

    /**
     * Current dispute status.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "dispute_status", nullable = false, length = 50)
    @Builder.Default
    private DisputeStatus disputeStatus = DisputeStatus.NONE;

    /**
     * Creation timestamp.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Last update timestamp.
     */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private Instant updatedAt;

    /**
     * Dispute status enumeration.
     * NONE, PENDING, RESOLVED_REFUND, RESOLVED_NO_REFUND.
     */
    public enum DisputeStatus {
        NONE,
        PENDING,
        RESOLVED_REFUND,
        RESOLVED_NO_REFUND
    }
}
