package com.carebridge.backend.health.entity;

public enum MetricType {
    WEIGHT,
    HYDRATION,
    MOOD,
    EPDS_SCORE,
    BLOOD_PRESSURE,
    BLOOD_PRESSURE_SYSTOLIC,
    BLOOD_PRESSURE_DIASTOLIC,
    BLOOD_GLUCOSE,
    FETAL_MOVEMENT_SESSION,
    FETAL_MOVEMENT_COUNT,
    HEART_RATE,
    SLEEP_DURATION,
    STEPS_COUNT,
    SPO2,
    TEMPERATURE,
    OTHER
}
