// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfRpZazA7I-Hx6RxYCEIjeTkXpqbwmVVY',
    appId: '1:772548995876:web:570bb88680e8f883f261b1',
    messagingSenderId: '772548995876',
    projectId: 'project-d04b488f-17fb-4ae5-b64',
    authDomain: 'project-d04b488f-17fb-4ae5-b64.firebaseapp.com',
    storageBucket: 'project-d04b488f-17fb-4ae5-b64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9H059fpMXz5HCJzKFYgEsP5oUO806ESw',
    appId: '1:772548995876:ios:4990ba914a2228f3f261b1',
    messagingSenderId: '772548995876',
    projectId: 'project-d04b488f-17fb-4ae5-b64',
    storageBucket: 'project-d04b488f-17fb-4ae5-b64.firebasestorage.app',
    iosBundleId: 'com.carebridge.g79.mobile',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfRpZazA7I-Hx6RxYCEIjeTkXpqbwmVVY',
    appId: '1:772548995876:android:725c8b5f57b8ebd6f261b1',
    messagingSenderId: '772548995876',
    projectId: 'project-d04b488f-17fb-4ae5-b64',
    storageBucket: 'project-d04b488f-17fb-4ae5-b64.firebasestorage.app',
  );
}
