package com.carebridge.backend.partner;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
import com.carebridge.backend.audit.entity.AuditAction;import com.carebridge.backend.audit.service.AuditService;import com.carebridge.backend.partner.dto.request.PartnerDecisionRequest;import com.carebridge.backend.partner.entity.*;import com.carebridge.backend.partner.exception.PartnerException;import com.carebridge.backend.partner.repository.PartnerOrganizationRepository;import com.carebridge.backend.partner.service.PartnerApprovalServiceImpl;import java.util.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;
@ExtendWith(MockitoExtension.class)class PartnerApprovalServiceImplTest{static final UUID ADMIN=UUID.fromString("fc000000-0000-0000-0000-0000000000ad"),PARTNER=UUID.fromString("fd000000-0000-0000-0000-000000000001");@Mock PartnerOrganizationRepository repo;@Mock AuditService audit;@InjectMocks PartnerApprovalServiceImpl service;PartnerOrganization org(OrganizationStatus s){return PartnerOrganization.builder().id(PARTNER).status(s).build();}void found(OrganizationStatus s){when(repo.findById(PARTNER)).thenReturn(Optional.of(org(s)));lenient().when(repo.save(any())).thenAnswer(i->i.getArgument(0));}PartnerDecisionRequest req(PartnerDecision d,String r){return new PartnerDecisionRequest(d,r);}
@Test void appTc601_approvePending(){found(OrganizationStatus.PENDING_APPROVAL);var r=service.decide(PARTNER,req(PartnerDecision.APPROVE,null),ADMIN);assertEquals(OrganizationStatus.APPROVED,r.newStatus());assertEquals(OrganizationStatus.PENDING_APPROVAL,r.previousStatus());}
@Test void appTc602_rejectPendingWithReason(){found(OrganizationStatus.PENDING_APPROVAL);assertEquals(OrganizationStatus.REJECTED,service.decide(PARTNER,req(PartnerDecision.REJECT,"missing license"),ADMIN).newStatus());}
@Test void appTc603_invalidTransitionsRejected(){Object[][] cases={{OrganizationStatus.APPROVED,PartnerDecision.APPROVE},{OrganizationStatus.REJECTED,PartnerDecision.APPROVE},{OrganizationStatus.PENDING_APPROVAL,PartnerDecision.SUSPEND}};for(Object[] c:cases){reset(repo);found((OrganizationStatus)c[0]);assertEquals("PTR-020",assertThrows(PartnerException.class,()->service.decide(PARTNER,req((PartnerDecision)c[1],"reason"),ADMIN)).getCode());}}
@Test void appTc604_suspendApproved(){found(OrganizationStatus.APPROVED);assertEquals(OrganizationStatus.SUSPENDED,service.decide(PARTNER,req(PartnerDecision.SUSPEND,"policy"),ADMIN).newStatus());}
@Test void appTc605_reinstateSuspended(){found(OrganizationStatus.SUSPENDED);assertEquals(OrganizationStatus.APPROVED,service.decide(PARTNER,req(PartnerDecision.REINSTATE,null),ADMIN).newStatus());}
@Test void appTc606_adverseDecisionRequiresReason(){found(OrganizationStatus.PENDING_APPROVAL);assertEquals("PTR-021",assertThrows(PartnerException.class,()->service.decide(PARTNER,req(PartnerDecision.REJECT,null),ADMIN)).getCode());reset(repo);found(OrganizationStatus.APPROVED);assertEquals("PTR-021",assertThrows(PartnerException.class,()->service.decide(PARTNER,req(PartnerDecision.SUSPEND,"  "),ADMIN)).getCode());}
@Test void appTc607_missingPartnerThrowsPtr018(){when(repo.findById(PARTNER)).thenReturn(Optional.empty());assertEquals("PTR-018",assertThrows(PartnerException.class,()->service.decide(PARTNER,req(PartnerDecision.APPROVE,null),ADMIN)).getCode());}
@Test void appTc608_decisionAudited(){found(OrganizationStatus.PENDING_APPROVAL);service.decide(PARTNER,req(PartnerDecision.APPROVE,null),ADMIN);verify(audit).log(eq(AuditAction.PARTNER_PROFILE_DECISION),eq(ADMIN),eq("PartnerOrganization"),eq(PARTNER.toString()),any());}}
