package com.carebridge.backend.partner;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
import com.carebridge.backend.partner.dto.request.PerformanceFilter;import com.carebridge.backend.partner.entity.*;import com.carebridge.backend.partner.exception.PartnerException;import com.carebridge.backend.partner.repository.*;import com.carebridge.backend.partner.service.PartnerPerformanceServiceImpl;import java.time.LocalDate;import java.util.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;
@ExtendWith(MockitoExtension.class) class PartnerPerformanceServiceImplTest{static final UUID OWNER=UUID.fromString("fa000000-0000-0000-0000-000000000001"),ORG=UUID.fromString("fb000000-0000-0000-0000-00000000000a");@Mock PartnerOrganizationRepository orgRepo;@Mock PartnerServiceRepository serviceRepo;@Mock SponsoredCampaignRepository campaignRepo;@Mock PartnerExpertLinkRepository linkRepo;@InjectMocks PartnerPerformanceServiceImpl service;
PartnerOrganization org(){return PartnerOrganization.builder().id(ORG).status(OrganizationStatus.APPROVED).representativeUserId(OWNER).build();}void setup(List<Object[]>s,List<Object[]>c,long links){when(orgRepo.findByRepresentativeUserId(OWNER)).thenReturn(Optional.of(org()));when(serviceRepo.countByStatus(ORG)).thenReturn(s);when(campaignRepo.countByStatus(eq(ORG),any(),any())).thenReturn(c);when(linkRepo.countByPartnerIdAndStatus(ORG,"ACTIVE")).thenReturn(links);}
@Test void ppfTc501_returnsGroundedAggregates(){setup(List.<Object[]>of(new Object[]{ServiceApprovalStatus.APPROVED,5L}),List.<Object[]>of(new Object[]{CampaignApprovalStatus.PENDING,2L}),4);var r=service.getPerformance(new PerformanceFilter(null,null),OWNER);assertEquals(5,r.serviceListingsByStatus().get("APPROVED"));assertEquals(2,r.campaignsByStatus().get("PENDING"));assertEquals(4,r.activeExpertLinks());}
@Test void ppfTc502_missingOrgThrowsPtr016(){when(orgRepo.findByRepresentativeUserId(OWNER)).thenReturn(Optional.empty());assertEquals("PTR-016",assertThrows(PartnerException.class,()->service.getPerformance(new PerformanceFilter(null,null),OWNER)).getCode());}
@Test void ppfTc505_countsOnlyActiveLinks(){setup(List.of(),List.of(),3);assertEquals(3,service.getPerformance(new PerformanceFilter(null,null),OWNER).activeExpertLinks());verify(linkRepo).countByPartnerIdAndStatus(ORG,"ACTIVE");}
@Test void ppfTc506_responseHasNoInventedMetrics(){setup(List.of(),List.of(),0);service.getPerformance(new PerformanceFilter(null,null),OWNER);var names=Arrays.stream(com.carebridge.backend.partner.dto.response.PartnerPerformanceResponse.class.getRecordComponents()).map(java.lang.reflect.RecordComponent::getName).toList();assertTrue(names.stream().noneMatch(n->n.matches("(?i).*(referral|click|conversion|view|revenue).*")));}
@Test void ppfTc507_emptyDataReturnsEmptyMaps(){setup(List.of(),List.of(),0);var r=service.getPerformance(new PerformanceFilter(null,null),OWNER);assertTrue(r.serviceListingsByStatus().isEmpty());assertTrue(r.campaignsByStatus().isEmpty());assertEquals(0,r.activeExpertLinks());}}
