package com.carebridge.backend.partner;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;import com.carebridge.backend.audit.entity.AuditAction;import com.carebridge.backend.audit.service.AuditService;import com.carebridge.backend.partner.dto.request.ContentDecisionRequest;import com.carebridge.backend.partner.entity.*;import com.carebridge.backend.partner.exception.PartnerException;import com.carebridge.backend.partner.repository.*;import com.carebridge.backend.partner.service.SponsoredApprovalServiceImpl;import java.util.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.MockitoExtension;
@ExtendWith(MockitoExtension.class)class SponsoredApprovalServiceImplTest{static final UUID ADMIN=UUID.fromString("fe000000-0000-0000-0000-0000000000ad"),CAMPAIGN=UUID.fromString("ff000000-0000-0000-0000-00000000000c"),SERVICE=UUID.fromString("ff000000-0000-0000-0000-00000000000d");@Mock PartnerServiceRepository serviceRepo;@Mock SponsoredCampaignRepository campaignRepo;@Mock AuditService audit;@InjectMocks SponsoredApprovalServiceImpl service;SponsoredCampaign campaign(CampaignApprovalStatus s){return SponsoredCampaign.builder().id(CAMPAIGN).approvalStatus(s).build();}PartnerService listing(ServiceApprovalStatus s){return PartnerService.builder().id(SERVICE).approvalStatus(s).build();}ContentDecisionRequest req(ContentDecision d,String r){return new ContentDecisionRequest(d,r);}
@Test void ascTc701_approveCampaignSetsReviewer(){when(campaignRepo.findById(CAMPAIGN)).thenReturn(Optional.of(campaign(CampaignApprovalStatus.PENDING)));var r=service.decide(PartnerContentTargetType.CAMPAIGN,CAMPAIGN,req(ContentDecision.APPROVE,null),ADMIN);assertEquals("APPROVED",r.newStatus());ArgumentCaptor<SponsoredCampaign>c=ArgumentCaptor.forClass(SponsoredCampaign.class);verify(campaignRepo).save(c.capture());assertEquals(ADMIN,c.getValue().getReviewedBy());}
@Test void ascTc702_rejectCampaign(){when(campaignRepo.findById(CAMPAIGN)).thenReturn(Optional.of(campaign(CampaignApprovalStatus.PENDING)));assertEquals("REJECTED",service.decide(PartnerContentTargetType.CAMPAIGN,CAMPAIGN,req(ContentDecision.REJECT,"policy"),ADMIN).newStatus());}
@Test void ascTc703_alreadyDecidedRejected(){when(campaignRepo.findById(CAMPAIGN)).thenReturn(Optional.of(campaign(CampaignApprovalStatus.APPROVED)));assertEquals("PTR-024",assertThrows(PartnerException.class,()->service.decide(PartnerContentTargetType.CAMPAIGN,CAMPAIGN,req(ContentDecision.REJECT,"x"),ADMIN)).getCode());}
@Test void ascTc704_approveServiceWithoutReviewerField(){when(serviceRepo.findById(SERVICE)).thenReturn(Optional.of(listing(ServiceApprovalStatus.PENDING)));assertEquals("APPROVED",service.decide(PartnerContentTargetType.SERVICE,SERVICE,req(ContentDecision.APPROVE,null),ADMIN).newStatus());assertTrue(Arrays.stream(PartnerService.class.getDeclaredFields()).noneMatch(f->f.getName().equals("reviewedBy")));}
@Test void ascTc705_rejectRequiresReason(){assertEquals("PTR-025",assertThrows(PartnerException.class,()->service.decide(PartnerContentTargetType.SERVICE,SERVICE,req(ContentDecision.REJECT,null),ADMIN)).getCode());}
@Test void ascTc707_missingTarget(){when(serviceRepo.findById(SERVICE)).thenReturn(Optional.empty());assertEquals("PTR-022",assertThrows(PartnerException.class,()->service.decide(PartnerContentTargetType.SERVICE,SERVICE,req(ContentDecision.APPROVE,null),ADMIN)).getCode());}
@Test void ascTc708_auditsBothTypes(){when(serviceRepo.findById(SERVICE)).thenReturn(Optional.of(listing(ServiceApprovalStatus.PENDING)));service.decide(PartnerContentTargetType.SERVICE,SERVICE,req(ContentDecision.APPROVE,null),ADMIN);verify(audit).log(eq(AuditAction.PARTNER_CONTENT_DECISION),eq(ADMIN),eq("SERVICE"),eq(SERVICE.toString()),any());}}
