import { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { getCredentialFileUrl, getExpertReviewCase, getIdentityFileUrl, type ExpertReviewCaseResponse } from '../../expert/services/expertApi';

const labels: Record<string, string> = { APPROVED: 'Đã duyệt', PENDING: 'Chờ xét duyệt', UNDER_REVIEW: 'Đang xét duyệt', PENDING_REVIEW: 'Chờ xét duyệt', REJECTED: 'Từ chối', SUSPENDED: 'Tạm ngưng', REVOKED: 'Thu hồi', MISSING: 'Chưa nộp' };
const credentialLabels: Record<string, string> = { CERTIFICATE: 'Chứng chỉ đào tạo', DEGREE: 'Bằng cấp học vị', MEDICAL_LICENSE: 'Chứng chỉ hành nghề y tế', PROFESSIONAL_LICENSE: 'Giấy phép hành nghề', IDENTITY_DOCUMENT: 'Giấy tờ định danh' };
function badge(value?: string | null) { const status = value || 'MISSING'; const color = ['APPROVED', 'ACTIVE'].includes(status) ? 'bg-emerald-100 text-emerald-700' : ['REJECTED', 'REVOKED'].includes(status) ? 'bg-rose-100 text-rose-700' : status === 'SUSPENDED' ? 'bg-orange-100 text-orange-700' : 'bg-amber-100 text-amber-800'; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${color}`}>{labels[status] || status.replaceAll('_', ' ')}</span>; }
function date(value?: string | null) { return value ? new Intl.DateTimeFormat('vi-VN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Chưa có'; }

export default function ExpertDetailPage() {
  const { expertProfileId } = useParams<{ expertProfileId: string }>();
  const navigate = useNavigate();
  const [item, setItem] = useState<ExpertReviewCaseResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!expertProfileId) return; setLoading(true); setError(null); try { setItem(await getExpertReviewCase(expertProfileId)); } catch { setError('Không thể tải hồ sơ chuyên gia hoặc hồ sơ không tồn tại.'); } finally { setLoading(false); } }, [expertProfileId]);
  useEffect(() => { void load(); }, [load]);
  const openIdentity = async (fileId?: string) => { if (!fileId) return; try { window.open(await getIdentityFileUrl(fileId), '_blank', 'noopener,noreferrer'); } catch { setError('Không thể mở tài liệu định danh.'); } };
  const openCredential = async (credentialId: string) => { try { window.open(await getCredentialFileUrl(credentialId), '_blank', 'noopener,noreferrer'); } catch { setError('Không thể mở chứng chỉ.'); } };
  if (loading) return <div className="min-h-screen bg-[#f7f9fb] p-8"><div className="mx-auto h-72 max-w-[1400px] animate-pulse rounded-2xl bg-white" /></div>;
  if (!item) return <main className="min-h-screen bg-[#f7f9fb] p-8"><div className="mx-auto max-w-[1400px] rounded-2xl border border-rose-200 bg-rose-50 p-8 text-center text-rose-800"><p className="font-bold">{error}</p><button type="button" onClick={() => navigate('/admin/experts')} className="mt-4 rounded-xl border border-[#d5dde2] bg-white px-4 py-2 text-sm font-semibold text-[#42515a]">Quay lại danh sách chuyên gia</button></div></main>;
  const { profile, latestIdentity, credentials } = item;
  return <main className="min-h-screen bg-[#f7f9fb] p-4 font-sans text-[#172126] lg:p-8"><div className="mx-auto max-w-[1400px] space-y-6">
    <button type="button" onClick={() => navigate('/admin/experts')} className="inline-flex items-center gap-2 rounded-full border border-[#d5dde2] bg-white px-3 py-1.5 text-xs font-semibold text-[#42515a] hover:bg-[#f6f8fa]"><span className="material-symbols-outlined text-base">arrow_back</span> Danh sách chuyên gia</button>
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{error}</div>}
    <header className="rounded-2xl border border-[#d5dde2] bg-white p-6 shadow-xs md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div className="flex min-w-0 items-center gap-5">{profile.avatarUrl ? <img src={profile.avatarUrl} alt="" className="h-16 w-16 rounded-full object-cover" /> : <div className="flex h-16 w-16 items-center justify-center rounded-full bg-[#d6f0ec] text-2xl font-bold text-[#0f766e]">{(profile.displayName || 'C').slice(0, 1)}</div>}<div><p className="mb-1 text-xs font-semibold uppercase tracking-wider text-[#0f766e]">Hồ sơ chuyên gia</p><h1 className="m-0 text-2xl font-bold">{profile.displayName || 'Chuyên gia chưa cập nhật tên'}</h1><p className="mb-0 mt-1 text-sm text-[#42515a]">{profile.professionalTitle || 'Chưa cập nhật chức danh'} · {profile.specialty || 'Chưa cập nhật chuyên khoa'}</p></div></div><div className="flex flex-wrap gap-2">{badge(profile.verificationStatus)}{badge(profile.trustStatus)}</div></div></header>
    <section className="grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2"><article className="rounded-2xl border border-[#d5dde2] bg-white p-6 shadow-xs"><h2 className="mb-5 flex items-center gap-2 text-lg font-bold"><span className="material-symbols-outlined text-[#0f766e]">person</span> Thông tin đăng ký & hồ sơ</h2><dl className="grid gap-x-8 gap-y-5 sm:grid-cols-2"><div><dt className="text-xs font-semibold uppercase text-[#6b7882]">Nơi công tác</dt><dd className="mt-1 text-sm">{profile.workplace || 'Chưa cập nhật'}</dd></div><div><dt className="text-xs font-semibold uppercase text-[#6b7882]">Kinh nghiệm</dt><dd className="mt-1 text-sm">{profile.experienceYears === null ? 'Chưa cập nhật' : `${profile.experienceYears} năm`}</dd></div><div><dt className="text-xs font-semibold uppercase text-[#6b7882]">Phạm vi tư vấn</dt><dd className="mt-1 whitespace-pre-wrap text-sm">{profile.consultationScope || 'Chưa cập nhật'}</dd></div><div><dt className="text-xs font-semibold uppercase text-[#6b7882]">Ngày đăng ký</dt><dd className="mt-1 text-sm">{date(profile.createdAt)}</dd></div><div><dt className="text-xs font-semibold uppercase text-[#6b7882]">Xét duyệt lần cuối</dt><dd className="mt-1 text-sm">{date(profile.verifiedAt)}</dd></div><div><dt className="text-xs font-semibold uppercase text-[#6b7882]">Điểm đánh giá</dt><dd className="mt-1 text-sm">{profile.ratingAvg ?? 'Chưa có'}</dd></div></dl></article>
      <article className="rounded-2xl border border-[#d5dde2] bg-white p-6 shadow-xs"><h2 className="mb-5 flex items-center gap-2 text-lg font-bold"><span className="material-symbols-outlined text-[#0f766e]">badge</span> Định danh cá nhân</h2>{latestIdentity ? <div className="space-y-4"><div className="flex flex-wrap items-center gap-3">{badge(item.identityStatus)}<span className="text-sm text-[#42515a]">Gửi lúc {date(latestIdentity.createdAt)}</span>{latestIdentity.faceSimilarity != null && <span className="text-sm text-[#42515a]">Độ khớp khuôn mặt: {Math.round(latestIdentity.faceSimilarity * 100)}%</span>}</div>{latestIdentity.reviewReason && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">Lý do: {latestIdentity.reviewReason}</p>}<div className="flex flex-wrap gap-2">{[['Ảnh chân dung', latestIdentity.selfieFileId], ['CCCD mặt trước', latestIdentity.identityFrontFileId], ['CCCD mặt sau', latestIdentity.identityBackFileId]].map(([label, fileId]) => <button key={String(label)} type="button" disabled={!fileId} onClick={() => void openIdentity(fileId)} className="rounded-xl border border-[#d5dde2] px-3 py-2 text-sm font-semibold text-[#0f766e] hover:bg-[#d6f0ec] disabled:cursor-not-allowed disabled:opacity-40"><span className="material-symbols-outlined mr-1 align-bottom text-base">open_in_new</span>{label}</button>)}</div></div> : <p className="text-sm text-[#6b7882]">Chuyên gia chưa gửi tài liệu định danh.</p>}</article>
      <article className="rounded-2xl border border-[#d5dde2] bg-white p-6 shadow-xs"><h2 className="mb-5 flex items-center gap-2 text-lg font-bold"><span className="material-symbols-outlined text-[#0f766e]">description</span> Chứng chỉ & giấy tờ chuyên môn</h2>{credentials.length === 0 ? <p className="text-sm text-[#6b7882]">Chuyên gia chưa nộp chứng chỉ chuyên môn.</p> : <div className="space-y-3">{credentials.map((credential) => <div key={credential.credentialId} className="flex flex-col gap-3 rounded-xl border border-[#eef3f6] bg-[#f7f9fb] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="m-0 font-semibold text-sm">{credentialLabels[credential.credentialType] || credential.credentialType}</p><p className="mt-1 text-xs text-[#6b7882]">{credential.issuer || 'Chưa rõ nơi cấp'} · {credential.credentialNumber || 'Không có số hiệu'} · Gửi {date(credential.createdAt)}</p>{credential.reviewNote && <p className="mb-0 mt-2 text-xs text-rose-700">Ghi chú xét duyệt: {credential.reviewNote}</p>}</div><div className="flex items-center gap-2">{badge(credential.reviewStatus)}<button type="button" onClick={() => void openCredential(credential.credentialId)} className="rounded-lg px-2 py-1.5 text-sm font-semibold text-[#0f766e] hover:bg-[#d6f0ec]">Mở</button></div></div>)}</div>}</article>
    </div><aside className="space-y-4"><section className="rounded-2xl border border-[#d5dde2] bg-white p-5 shadow-xs"><h2 className="m-0 text-base font-bold">Tiến độ xét duyệt</h2><div className="mt-5 space-y-4"><div className="flex items-center justify-between"><span className="text-sm text-[#42515a]">Định danh</span>{badge(item.identityStatus)}</div><div className="flex items-center justify-between"><span className="text-sm text-[#42515a]">Chứng chỉ</span>{badge(item.credentialStatus)}</div><div className="flex items-center justify-between"><span className="text-sm text-[#42515a]">Hồ sơ cuối</span>{badge(profile.verificationStatus)}</div></div></section><section className="rounded-2xl border border-[#95d2ca] bg-[#d6f0ec]/50 p-5"><p className="m-0 text-sm font-bold text-[#0f5a53]">Điều kiện phê duyệt</p><p className="mb-0 mt-2 text-sm text-[#42515a]">{item.readyForFinalApproval ? 'Hồ sơ đã đủ các điều kiện định danh và chứng chỉ để được phê duyệt.' : 'Hồ sơ chưa đủ điều kiện phê duyệt cuối hoặc đã được xử lý.'}</p></section></aside></section>
  </div></main>;
}
