/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#d6c2bd',
        'tertiary-fixed': '#e9e1db',
        'surface-container': '#ffe9e3',
        'on-error-container': '#93000a',
        'surface-container-highest': '#fadcd3',
        'secondary': '#6e5a52',
        'primary-fixed': '#ffdbd1',
        'surface-container-high': '#ffe2d9',
        'on-tertiary-container': '#36322e',
        'surface-container-low': '#fff1ec',
        'on-surface': '#271812',
        'on-primary-container': '#51271b',
        'on-primary-fixed-variant': '#693a2d',
        'error': '#ba1a1a',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#4a4642',
        'surface-dim': '#f1d4ca',
        'secondary-fixed-dim': '#dbc1b7',
        'background': '#fff8f6',
        'primary-fixed-dim': '#fab7a4',
        'on-error': '#ffffff',
        'tertiary': '#625d59',
        'on-tertiary-fixed': '#1e1b18',
        'on-tertiary': '#ffffff',
        'outline': '#84736f',
        'inverse-on-surface': '#ffede7',
        'secondary-container': '#f6dacf',
        'inverse-primary': '#fab7a4',
        'tertiary-container': '#a09a95',
        'surface-bright': '#fff8f6',
        'tertiary-fixed-dim': '#ccc5c0',
        'on-surface-variant': '#524440',
        'primary': '#845143',
        'on-primary-fixed': '#341006',
        'on-background': '#271812',
        'on-secondary-container': '#735e56',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'surface-variant': '#fadcd3',
        'surface': '#ffffff',
        'secondary-fixed': '#f8ddd2',
        'inverse-surface': '#3e2c26',
        'on-secondary-fixed': '#271812',
        'primary-container': '#c98c7b',
        'surface-tint': '#845143',
        'on-secondary-fixed-variant': '#55433b',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Lexend', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'button': ['15px', { lineHeight: '20px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
