/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#d5dde2',
        'tertiary-fixed': '#e6ebef',
        'surface-container': '#eef3f6',
        'on-error-container': '#93000a',
        'surface-container-highest': '#dbe4e9',
        'secondary': '#51606a',
        'primary-fixed': '#cce8e4',
        'surface-container-high': '#e6edf1',
        'on-tertiary-container': '#263238',
        'surface-container-low': '#f6f8fa',
        'on-surface': '#172126',
        'on-primary-container': '#043733',
        'on-primary-fixed-variant': '#0f5a53',
        'error': '#ba1a1a',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#3f4d55',
        'surface-dim': '#e6eaed',
        'secondary-fixed-dim': '#c5d0d7',
        'background': '#f7f9fb',
        'primary-fixed-dim': '#95d2ca',
        'on-error': '#ffffff',
        'tertiary': '#59636a',
        'on-tertiary-fixed': '#12191d',
        'on-tertiary': '#ffffff',
        'outline': '#6b7882',
        'inverse-on-surface': '#ffede7',
        'secondary-container': '#dce5ea',
        'inverse-primary': '#fab7a4',
        'tertiary-container': '#bac5cc',
        'surface-bright': '#ffffff',
        'tertiary-fixed-dim': '#c8d1d7',
        'on-surface-variant': '#42515a',
        'primary': '#0f766e',
        'on-primary-fixed': '#00201d',
        'on-background': '#172126',
        'on-secondary-container': '#2f3d45',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'surface-variant': '#e6edf1',
        'surface': '#ffffff',
        'secondary-fixed': '#e1e9ee',
        'inverse-surface': '#2c353a',
        'on-secondary-fixed': '#172126',
        'primary-container': '#d6f0ec',
        'surface-tint': '#0f766e',
        'on-secondary-fixed-variant': '#42515a',
      },
      borderRadius: {
        DEFAULT: '6px',
        md: '8px',
        lg: '12px',
        full: '9999px',
      },
      fontFamily: {
        sans: ['"SF Pro Text"', '"Segoe UI"', 'Roboto', 'Arial', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['28px', { lineHeight: '36px', letterSpacing: '0', fontWeight: '700' }],
        'headline-lg': ['22px', { lineHeight: '30px', letterSpacing: '0', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '26px', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['15px', { lineHeight: '23px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['11px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'button': ['13px', { lineHeight: '18px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
