ALTER TABLE baby_profiles
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS ux_baby_profiles_owner_active
    ON baby_profiles(owner_user_id)
    WHERE is_active = true;

ALTER TABLE baby_daily_logs
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';

CREATE INDEX IF NOT EXISTS idx_baby_daily_logs_baby_status_created
    ON baby_daily_logs(baby_id, status, created_at);

ALTER TABLE development_milestones
    ADD COLUMN IF NOT EXISTS milestone_status VARCHAR(20) NOT NULL DEFAULT 'ACHIEVED',
    ADD COLUMN IF NOT EXISTS record_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';

CREATE INDEX IF NOT EXISTS idx_development_milestones_baby_record_status
    ON development_milestones(baby_id, record_status);

ALTER TABLE audit_logs
    DROP CONSTRAINT IF EXISTS audit_logs_action_check;

ALTER TABLE audit_logs
    ADD CONSTRAINT audit_logs_action_check CHECK (
        action IN (
            'LOGIN', 'LOGOUT', 'OTP_SENT', 'OTP_VERIFIED', 'OTP_RESENT',
            'CONSENT_GRANTED', 'CONSENT_REVOKED', 'CREATE_HEALTH_RECORD', 'VIEW_HEALTH_RECORD',
            'EXPERT_VERIFICATION', 'MODERATION_ACTION', 'AI_TRIAGE', 'PAYMENT', 'SECURITY_EVENT',
            'VIEW_AUDIT_LOG', 'USER_REGISTRATION_COMPLETED', 'SESSION_REVOKED', 'CONTENT_CREATED',
            'CONTENT_UPDATED', 'CONTENT_HIDDEN', 'PARTNER_PROFILE_CREATED', 'COMMUNITY_QUESTION_CREATED',
            'COMMUNITY_QUESTION_EDITED', 'COMMUNITY_ANSWER_POSTED', 'COMMUNITY_ANSWER_LIKED',
            'COMMUNITY_BOOKMARK_TOGGLED', 'COMMUNITY_ANSWER_UNLIKED', 'MODERATION_QUEUE_VIEWED',
            'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED', 'PASSWORD_CHANGED', 'PROFILE_UPDATED',
            'PROFILE_VIEWED', 'PRIVACY_SETTINGS_ACCESSED', 'PRIVACY_SETTINGS_UPDATED', 'NOTIFICATION_SENT',
            'NOTIFICATION_FAILED', 'SECURITY_INCIDENT_INVESTIGATED', 'SECURITY_EVENT_REVIEWED',
            'SECURITY_NOTE_ADDED', 'JOURNEY_CREATED', 'JOURNEY_UPDATED', 'BABY_PROFILE_CREATED',
            'BABY_PROFILE_UPDATED', 'BABY_PROFILE_ARCHIVED', 'BABY_ACTIVE_PROFILE_SWITCHED',
            'HEALTH_RECORD_ADDED', 'HEALTH_RECORD_UPDATED', 'HEALTH_RECORD_ARCHIVED', 'HEALTH_METRIC_ADDED',
            'HEALTH_METRIC_UPDATED', 'METRIC_ADDED', 'METRIC_UPDATED', 'POSTPARTUM_LOG_ADDED',
            'POSTPARTUM_LOG_UPDATED', 'POSTPARTUM_LOG_DELETED', 'HEALTH_METRIC_DELETED',
            'REMINDER_CREATED', 'CARE_GROUP_CREATED', 'CARE_GROUP_MEMBER_INVITED',
            'CARE_GROUP_INVITE_ACCEPTED', 'CARE_GROUP_INVITE_DECLINED', 'CARE_GROUP_INVITE_REVOKED',
            'CARE_GROUP_MEMBER_REMOVED', 'CARE_GROUP_MEMBER_LEFT', 'CARE_GROUP_PERMISSION_UPDATED',
            'FILE_UPLOADED', 'FILE_VIEWED', 'FILE_DELETED', 'NOTIFICATION_PREFERENCES_UPDATED',
            'NOTIFICATION_PREFERENCES_VIEWED', 'NOTIFICATIONS_READ', 'COMMUNITY_QUESTION_DELETED',
            'COMMUNITY_ANSWER_EDITED', 'COMMUNITY_ANSWER_DELETED', 'CONTENT_DECIDED',
            'RED_FLAG_RULE_CREATED', 'RED_FLAG_RULE_UPDATED', 'RED_FLAG_RULE_DELETED',
            'COMMUNITY_QUESTION_LIKED', 'COMMUNITY_QUESTION_UNLIKED', 'USER_ACCOUNT_STATUS_CHANGED',
            'STAFF_ACCOUNT_CREATED', 'ROLE_PERMISSION_UPDATED', 'POSTURE_CONFIG_CREATED',
            'POSTURE_CONFIG_UPDATED', 'POSTURE_CONFIG_ACTIVATED', 'EXERCISE_CREATED',
            'EXERCISE_UPDATED', 'EXERCISE_ACTIVATED', 'EXERCISE_DISABLED', 'CONTENT_REPORTED',
            'COMMUNITY_PROFILE_CREATED', 'COMMUNITY_PROFILE_UPDATED', 'BABY_LOG_ADDED',
            'BABY_LOG_UPDATED', 'BABY_LOG_DELETED', 'BABY_DAILY_LOG_DELETED', 'MILESTONE_RECORDED', 'MILESTONE_UPDATED',
            'MILESTONE_DELETED', 'HEALTH_SUMMARY_GENERATED', 'HEALTH_SUMMARY_SHARED',
            'VACCINATION_RECORD_ADDED', 'VACCINATION_RECORD_UPDATED', 'VACCINATION_RECORD_DELETED',
            'VACCINATION_COMPLETED', 'VACCINATION_POSTPONED', 'GROWTH_MEASUREMENT_ADDED',
            'GROWTH_MEASUREMENT_UPDATED', 'GROWTH_MEASUREMENT_DELETED', 'EXPENSE_CREATED',
            'EXPENSE_UPDATED', 'EXPENSE_DELETED', 'CHECKLIST_ITEM_ADDED', 'CHECKLIST_ITEM_COMPLETED',
            'CHECKLIST_ITEM_UPDATED', 'CHECKLIST_ITEM_DELETED', 'CARE_TASK_ASSIGNED',
            'CARE_TASK_UPDATED', 'CARE_TASK_CANCELLED', 'CARE_GROUP_INVITATION_ACCEPTED',
            'CARE_TASK_STATUS_UPDATED', 'FAMILY_ALERT_VIEWED'
        )
    );
