UPDATE public.health_metric_definitions
SET display_name = 'Nhịp tim',
    observation_shape = 'POINT',
    manual_entry_supported = true,
    device_import_supported = true,
    canonical_unit = 'bpm',
    accepted_input_units_jsonb = '["bpm"]'::jsonb,
    precision_scale = 0,
    required_context_schema_jsonb = '{"required":[],"optional":["measurementState","deviceName","sourceApp"]}'::jsonb,
    plausibility_policy_jsonb = '{"range":{"min":30,"max":250}}'::jsonb,
    aggregation_policy_jsonb = '{"method":"REPRESENTATIVE_DAILY_POINT"}'::jsonb,
    chart_policy_jsonb = '{"type":"LINE","xAxis":"DATE"}'::jsonb,
    quality_policy_jsonb = '{"required":false,"source":"SMART_WATCH"}'::jsonb,
    allowed_journey_stages_jsonb = '["PRE_PREGNANCY", "PREGNANCY", "POSTPARTUM"]'::jsonb,
    is_active = true,
    effective_until = NULL,
    updated_at = now()
WHERE metric_code = 'MATERNAL_HEART_RATE'
  AND version = 1;

INSERT INTO public.health_metric_definitions (
    metric_code,
    version,
    display_name,
    observation_shape,
    manual_entry_supported,
    device_import_supported,
    canonical_unit,
    accepted_input_units_jsonb,
    precision_scale,
    required_context_schema_jsonb,
    plausibility_policy_jsonb,
    aggregation_policy_jsonb,
    chart_policy_jsonb,
    quality_policy_jsonb,
    allowed_journey_stages_jsonb
)
VALUES (
    'STRESS',
    1,
    'Stress',
    'POINT',
    true,
    true,
    'điểm',
    '["điểm"]'::jsonb,
    0,
    '{"required":[],"optional":["deviceName","sourceApp"]}'::jsonb,
    '{"range":{"min":0,"max":100}}'::jsonb,
    '{"method":"REPRESENTATIVE_DAILY_POINT"}'::jsonb,
    '{"type":"LINE","xAxis":"DATE"}'::jsonb,
    '{"required":false,"source":"SMART_WATCH"}'::jsonb,
    '["PRE_PREGNANCY", "PREGNANCY", "POSTPARTUM"]'::jsonb
)
ON CONFLICT (metric_code, version) DO UPDATE
SET display_name = EXCLUDED.display_name,
    observation_shape = EXCLUDED.observation_shape,
    manual_entry_supported = EXCLUDED.manual_entry_supported,
    device_import_supported = EXCLUDED.device_import_supported,
    canonical_unit = EXCLUDED.canonical_unit,
    accepted_input_units_jsonb = EXCLUDED.accepted_input_units_jsonb,
    precision_scale = EXCLUDED.precision_scale,
    required_context_schema_jsonb = EXCLUDED.required_context_schema_jsonb,
    plausibility_policy_jsonb = EXCLUDED.plausibility_policy_jsonb,
    aggregation_policy_jsonb = EXCLUDED.aggregation_policy_jsonb,
    chart_policy_jsonb = EXCLUDED.chart_policy_jsonb,
    quality_policy_jsonb = EXCLUDED.quality_policy_jsonb,
    allowed_journey_stages_jsonb = EXCLUDED.allowed_journey_stages_jsonb,
    is_active = true,
    effective_until = NULL,
    updated_at = now();
