"""AI Nurse Assistant RAG Chat Service (Step 10 in Workflow)."""

from __future__ import annotations

import logging
from typing import List
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import MEDICAL_DISCLAIMER
from app.core.gemini import get_gemini_client
from app.models.schemas import (
    RagChatRequest,
    RagChatResponse,
    SourceCitation,
)
from app.rag.prompts import (
    NURSE_ASSISTANT_SYSTEM_PROMPT,
    build_rag_chat_prompt,
)
from app.rag.vector_store import get_vector_store

logger = logging.getLogger(__name__)


class RagChatService:
    def __init__(self) -> None:
        self.gemini = get_gemini_client()
        self.vector_store = get_vector_store()

    async def chat(
        self,
        request: RagChatRequest,
        session: AsyncSession | None = None,
    ) -> RagChatResponse:
        """Process user message, retrieve relevant medical chunks, and generate grounded answer via Gemini Flash."""
        # 1. Build Context-Aware Vector Search Query
        # If user refers to previous context (e.g., "nó có nguy hiểm không?"), merge with recent symptoms
        search_query = request.message
        if request.conversation_history:
            recent_user_turns = [
                msg.content
                for msg in request.conversation_history[-4:]
                if msg.role.lower() in ("user", "human")
            ]
            if recent_user_turns:
                # Merge recent user mentions with current message for richer vector recall
                search_query = f"{' '.join(recent_user_turns)} {request.message}"

        # 2. Semantic Search across Maternal Knowledge pgvector
        stage_filter = request.stage.value if request.stage else "PREGNANCY"
        retrieved_chunks = await self.vector_store.similarity_search(
            query=search_query,
            stage=stage_filter,
            top_k=4,
            session=session,
        )

        # 3. Check for Critical Emergency Flags in the user's message & recent turns
        combined_text = f"{search_query} {request.message}"
        has_critical_warning = self._detect_emergency_intent(combined_text)

        # 4. Format Recent Metrics Context if provided
        recent_metrics_summary = None
        if request.recent_metrics:
            m = request.recent_metrics
            parts = []
            if m.systolic_bp and m.diastolic_bp:
                parts.append(f"Huyết áp {m.systolic_bp}/{m.diastolic_bp} mmHg")
            if m.temperature:
                parts.append(f"Thân nhiệt {m.temperature}°C")
            if m.blood_glucose:
                parts.append(f"Đường huyết {m.blood_glucose} mmol/L")
            if m.fetal_movements_count is not None:
                parts.append(f"Cử động thai {m.fetal_movements_count} lần")
            if m.symptoms:
                parts.append(f"Triệu chứng: {', '.join(m.symptoms)}")
            recent_metrics_summary = ", ".join(parts)

        # 5. Filter relevant chunks and Build Grounded Prompt with Conversation History
        valid_chunks = [
            c for c in retrieved_chunks
            if c.get("similarity") is None or c.get("similarity", 0.0) >= 0.05
        ]

        history_dicts = [
            {"role": msg.role, "content": msg.content}
            for msg in request.conversation_history
        ] if request.conversation_history else None

        prompt = build_rag_chat_prompt(
            user_message=request.message,
            context_chunks=valid_chunks,
            stage=stage_filter,
            gestational_age_weeks=request.gestational_age_weeks,
            recent_metrics_summary=recent_metrics_summary,
            conversation_history=history_dicts,
        )

        # 6. Call Gemini Flash Generator
        raw_answer = await self.gemini.generate_response(
            prompt=prompt,
            system_instruction=NURSE_ASSISTANT_SYSTEM_PROMPT,
        )

        # 7. Extract Dynamic Follow-up Suggestions generated by Gemini
        answer_text, dynamic_followups = self._extract_dynamic_followups(raw_answer)

        if has_critical_warning:
            emergency_chips = ["Gọi cấp cứu 115 ngay?", "Bệnh viện phụ sản gần nhất?"]
            dynamic_followups = (emergency_chips + [f for f in dynamic_followups if f not in emergency_chips])[:3]
        elif not dynamic_followups:
            dynamic_followups = self._generate_fallback_followups(has_critical_warning)

        # 8. Format Source Citations (Relevance Filter + Smart Deduplication)
        citations: List[SourceCitation] = []
        seen_keys = set()
        seen_titles_with_specific_sections = set()

        # First pass: identify titles that already have specific detailed sub-sections
        for doc in valid_chunks:
            t = doc.get("title", "Cẩm nang y tế").strip()
            s = (doc.get("section") or "").strip()
            if s and s.lower() != t.lower():
                seen_titles_with_specific_sections.add(t.lower())

        for doc in valid_chunks:
            title = doc.get("title", "Cẩm nang y tế").strip()
            section = (doc.get("section") or "").strip() or None

            # If section is identical to title, avoid repeating "(Title)"
            if section and section.lower() == title.lower():
                # If we already cite specific sections of this document, skip the generic root title chunk
                if title.lower() in seen_titles_with_specific_sections:
                    continue
                section = None

            key = f"{title.lower()}_{section.lower() if section else ''}"
            if key in seen_keys:
                continue
            seen_keys.add(key)

            citations.append(
                SourceCitation(
                    title=title,
                    source=doc.get("source", "Bộ Y Tế"),
                    section=section,
                    snippet=doc.get("content", "")[:250] + "...",
                    similarity_score=doc.get("similarity"),
                )
            )

        return RagChatResponse(
            answer=answer_text.strip(),
            has_critical_warning=has_critical_warning,
            suggested_followups=dynamic_followups,
            sources=citations,
            disclaimer=MEDICAL_DISCLAIMER,
        )

    def _extract_dynamic_followups(self, text: str) -> tuple[str, List[str]]:
        """Extracts dynamic follow-up questions generated by Gemini at the end of the response."""
        tag_candidates = [
            "[GỢI Ý CÂU HỎI]:",
            "[GỢI Ý CÂU HỎI TIẾP THEO]:",
            "[SUGGESTED_QUESTIONS]:",
            "[GỢI Ý]:",
        ]

        found_tag = None
        for tag in tag_candidates:
            if tag in text:
                found_tag = tag
                break

        if not found_tag:
            return text.strip(), []

        parts = text.split(found_tag, 1)
        main_answer = parts[0].strip()
        followup_raw = parts[1].strip()

        followups: List[str] = []
        for line in followup_raw.splitlines():
            cleaned = line.strip().lstrip("-*•123456789.) ").strip()
            if cleaned and len(cleaned) > 3:
                if not cleaned.endswith("?"):
                    cleaned += "?"
                followups.append(cleaned)

        return main_answer, followups[:3]

    def _detect_emergency_intent(self, message: str) -> bool:
        lower = message.lower()
        danger_signals = [
            "ra máu", "chảy máu", "vỡ ối", "rỉ ối", "co giật",
            "đau bụng dữ dội", "không thấy con đạp", "thai không cử động",
            "nhìn mờ", "hoa mắt dữ dội", "sốt cao 39", "sốt cao 40",
        ]
        return any(signal in lower for signal in danger_signals)

    def _generate_fallback_followups(self, is_emergency: bool) -> List[str]:
        """Minimal fallback only used if Gemini fails to provide dynamic follow-up tags."""
        if is_emergency:
            return [
                "Bệnh viện phụ sản gần nhất ở đâu?",
                "Gọi cấp cứu 115 như thế nào?",
                "Cần chuẩn bị giấy tờ gì khi vào viện cấp cứu?",
            ]
        return [
            "Các mốc khám thai quan trọng cần nhớ?",
            "Chế độ dinh dưỡng khoa học theo từng giai đoạn?",
            "Dấu hiệu bất thường cần đến cơ sở y tế?",
        ]


rag_chat_service = RagChatService()


def get_rag_chat_service() -> RagChatService:
    return rag_chat_service
